import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Promptify",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html
      className="bg-gradient-to-r from-orange-50 via-pink-50 to-orange-50 white"
      data-theme="cupcake"
      lang="en"
    >
      
      <body className={`${inter.className}`}>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
